### ISSUE TITLE
Response speed and voice 

### ISSUE THREAD

**Issue by imwebdev** [tartanguru/alexa-assistant#10]
Hi, 
This is a fantastic developer addon and works great. 
I tried to change the SEND_SPEED value to see if i could get a quicker response time, But on average the response takes about 10 seconds. Is there anyway to improve the performance? 
Also is there anyway to change the google voice? 

Thanks

**Comment by tartanguru** [comment]
The skill already sends audio to the API at 10 times real speed, but there
is always going to be a latency from the speech > text > speech > text
conversion as as well as the transcoding of the audio.
The biggest delay is having to wait for the whole audio response from alexa
to be sent to google and then the response to be sent before it can be
played by alexa. Real google devices can stream the audio from the
microphone to the api as you are talking and then play the audio back to
the speakers as soon as it arrives
If you set DEBUG_MODE to true then you can see what the various stages are
doing with regards to durations
