### ISSUE TITLE
Alexa says the skill isn't linked but it is. App works for less than hour.

### ISSUE THREAD

**Issue by Iangh59** [tartanguru/alexa-assistant#102]
It works fine but within an hour it stops and asks me to link the account. I go to the Alexa app and Alexa Assistant is still linked. To get it working I have to disable and re-enable. This happens whether I link via the Android Alexa app or desktop browser.

**Comment by Iangh59** [comment]
I have it working now. Started from scratch (deleted everything including Google key) and went slowly. It would be nice if somebody  (who knows what they are doing) could update instructions to reflect issue #95.

**Comment by Iangh59** [comment]
Had to go really slow, tried 5 times before getting it right as sometimes I got lost.

**Comment by trinib** [comment]
> 
> 
> Had to go really slow, tried 5 times before getting it right as sometimes I got lost.

what function you using ?? cloudformaation or lambda method ????

**Comment by Iangh59** [comment]
When you follow the instructions a alexa-assistant-skill-function lambda is created with a code size of about 10MB. Open it and in "Function Code/Actions" there is an option to upload the zip file from #95 . It should now say a code size of 26.9MB. Sorry, I don't understand why/how it works.

**Comment by trinib** [comment]
> 
> 
> When you follow the instructions a alexa-assistant-skill-function lambda is created with a code size of about 10MB. Open it and in "Function Code/Actions" there is an option to upload the zip file from #95 . It should now say a code size of 26.9MB. Sorry, I don't understand why/how it works.

i still get over 10mb from alexa-assistant-skill-function that was created when i made stack formation and edited *cloudformation.json with replacing nodejs6.10 to nodejs10.x just like in the instructions..did you did it like that to get 10mb from the function that was created ?or can you send me json file for stack part ..thanks for the help..
![shnd](https://user-images.githubusercontent.com/18756975/98456872-18b0a300-2158-11eb-83b2-d896f6dbde6d.png)

**Comment by Iangh59** [comment]
All I can is say I followed https://github.com/tartanguru/alexa-assistant/issues/95#issuecomment-696648685. I read #95 and also the original instructions, https://github.com/tartanguru/alexa-assistant-instructions/blob/master/fresh_install.md, and went very slow. The bit that I didn't initially get was uploading the zip file as per my last post because I'm a tad thick!:) It's as simple as bellindj makes out provided you go slow and follow the instructions to the letter. If I can get it working, anybody can. Good luck!

**Comment by trinib** [comment]
> All I can is say I followed https://github.com/tartanguru/alexa-assistant/issues/95#issuecomment-696648685. I read #95 and also the original instructions, https://github.com/tartanguru/alexa-assistant-instructions/blob/master/fresh_install.md, and went very slow. The bit that I didn't initially get was uploading the zip file as per my last post because I'm a tad thick!:) It's as simple as bellindj makes out provided you go slow and follow the instructions to the letter. If I can get it working, anybody can. Good luck!

ohh cool.. I tried all how lol.. can you copy and paste the json file you uploaded to cloudformation stack.. if you can

**Comment by Iangh59** [comment]
This is ever so much a  case of the blind leading the blind!:) Change .zip to .json


[cloudformation.zip](https://github.com/tartanguru/alexa-assistant/files/5505864/cloudformation.zip)

**Comment by trinib** [comment]
> 
> 
> This is ever so much a case of the blind leading the blind!:) Change .zip to .json
> 
> [cloudformation.zip](https://github.com/tartanguru/alexa-assistant/files/5505864/cloudformation.zip)

archive error ..just paste it ..i feel im using wrong file and code

**Comment by Iangh59** [comment]
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Metadata":{
        "License": "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License"
    },
    Description: "This AWS CloudFormation Template is provided for users to install the Alexa Google Assistant skill. It is provided under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License. This means that you may use this template provided that it is not for commercial use. You may not host instructions that use this CloudFormation template if you receive monetisation from that page, for example embedded adverts",
    "Mappings": {
        "RegionMap": {
            "us-east-1": {
                "BUCKET": "alexagoogleassistantskilluseast1"
            },
            "eu-west-1": {
                "BUCKET": "alexagoogleassistantskilleuwest1"
            }
        }
    },
    "Conditions": {
        "CorrectAWSRegion": {
            "Fn::Or": [
                {
                    "Fn::Equals": [
                        {
                            "Ref": "AWS::Region"
                        },
                        "eu-west-1"
                    ]
                },
                {
                    "Fn::Equals": [
                        {
                            "Ref": "AWS::Region"
                        },
                        "us-east-1"
                    ]
                }
            ]
        },
        "IncorrectAWSRegion": {
            "Fn::Not": [
                {
                    "Condition": "CorrectAWSRegion"
                }
            ]
        }
    },
    "Resources": {
        "S3Bucket": {
            "Type": "AWS::S3::Bucket",
            "Condition": "CorrectAWSRegion",
            "Properties": {
                
            }
        },
        "DynamoDBtable": {
                "Type" : "AWS::DynamoDB::Table",
            "Condition": "CorrectAWSRegion",
                "Properties" : {
                    "AttributeDefinitions" : [
                      {
                        "AttributeName" : "userId",
                        "AttributeType" : "S"   
                      }
                    ],
                  "KeySchema" : 
                      [
                          {
                            "AttributeName" : "userId",
                            "KeyType" : "HASH"
                          }
                      ]
                    
                    ,
                  "ProvisionedThroughput" : {
                    "ReadCapacityUnits" : 5,
                    "WriteCapacityUnits" : 5
                  },
                  "TableName": "AlexaAssistantSkillSettings"                       
                }
            
        },
        "LambdaFunctionRole": {
            "Type": "AWS::IAM::Role",
            "Condition": "CorrectAWSRegion",
            "Properties": {
                "AssumeRolePolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Principal": {
                                "Service": [
                                    "lambda.amazonaws.com"
                                ]
                            },
                            "Action": [
                                "sts:AssumeRole"
                            ]
                        }
                    ]
                },
                "Path": "/",
                "Policies": [
                    {
                        "PolicyName": "GoogleAssistantPolicy",
                        "PolicyDocument": {
                            "Version": "2012-10-17",
                            "Statement": [
                                {
                                    "Sid": "AllowLogging",
                                    "Effect": "Allow",
                                    "Action": [
                                        "logs:CreateLogGroup",
                                        "logs:CreateLogStream",
                                        "logs:PutLogEvents"
                                    ],
                                    "Resource": [
                                        "*"
                                    ]
                                },
                                {
                                    "Effect": "Allow",
                                    "Action": "s3:*",
                                    "Resource": [
                                        {
                                            "Fn::Join": [
                                                "",
                                                [
                                                    {
                                                        "Fn::GetAtt": [
                                                            "S3Bucket",
                                                            "Arn"
                                                        ]
                                                    },
                                                    "*"
                                                ]
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "Effect": "Allow",
                                    "Action": "dynamodb:*",
                                    "Resource": [
                                        {
                                            "Fn::Join": [
                                                "",
                                                [
                                                    {
                                                        "Fn::GetAtt": [
                                                            "DynamoDBtable",
                                                            "Arn"
                                                        ]
                                                    },
                                                    "*"
                                                ]
                                            ]
                                        }
                                    ]
                                }
                                
                            ]
                        }
                    }
                ]
            }
        },
        "AlexaSkillFunction": {
            "Type": "AWS::Lambda::Function",
            "Condition": "CorrectAWSRegion",
            "Properties": {
                "FunctionName": "alexa-assistant-skill-function",
                "Handler": "index.handler",
                "Role": {
                    "Fn::GetAtt": [
                        "LambdaFunctionRole",
                        "Arn"
                    ]
                },
                "Description": "Alexa Skill code for the Google Assistant Skill",
                "Code": {
                    "S3Bucket": {
                        "Fn::FindInMap": [
                            "RegionMap",
                            {
                                "Ref": "AWS::Region"
                            },
                            "BUCKET"
                        ]
                    },
                    "S3Key": "index_1.2.zip"
                },
                "Runtime": "nodejs10.x",
                "Timeout": "10",
                "MemorySize": "1344",
                "Environment": {
                    "Variables": {
                        "S3_BUCKET": {
                            "Ref": "S3Bucket"
                        },
                        "API_ENDPOINT": "embeddedassistant.googleapis.com"
                    }
                }
            }
        },
        "AlexaSkillFunctionPermissions": {
            "Type": "AWS::Lambda::Permission",
            "Condition": "CorrectAWSRegion",
            "Properties": {
                "FunctionName": {
                    "Ref": "AlexaSkillFunction"
                },
                "Action": "lambda:InvokeFunction",
                "Principal": "alexa-appkit.amazon.com"
            }
        }
    },
    "Outputs": {
        "FunctionARN": {
            "Condition": "CorrectAWSRegion",
            "Value": {
                "Fn::GetAtt": [
                    "AlexaSkillFunction",
                    "Arn"
                ]
            },
            "Description": "Lambda function ARN to be placed in the Amazon Developer Portal"
        },
        "FunctionError": {
            "Condition": "IncorrectAWSRegion",
            "Value": "Incorrect AWS Region!!! Must be US-East(N. VIRGINIA) or EU(Ireland)",
            "Description": "You must Select US-EAST (North Virgina) if you are located in North America or EU (Ireland) if you are located elsewhere"
        }
    }
}

**Comment by trinib** [comment]
> 
> 
> {
> "AWSTemplateFormatVersion": "2010-09-09",
> "Metadata":{
> "License": "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License"
> },
> Description: "This AWS CloudFormation Template is provided for users to install the Alexa Google Assistant skill. It is provided under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License. This means that you may use this template provided that it is not for commercial use. You may not host instructions that use this CloudFormation template if you receive monetisation from that page, for example embedded adverts",
> "Mappings": {
> "RegionMap": {
> "us-east-1": {
> "BUCKET": "alexagoogleassistantskilluseast1"
> },
> "eu-west-1": {
> "BUCKET": "alexagoogleassistantskilleuwest1"
> }
> }
> },
> "Conditions": {
> "CorrectAWSRegion": {
> "Fn::Or": [
> {
> "Fn::Equals": [
> {
> "Ref": "AWS::Region"
> },
> "eu-west-1"
> ]
> },
> {
> "Fn::Equals": [
> {
> "Ref": "AWS::Region"
> },
> "us-east-1"
> ]
> }
> ]
> },
> "IncorrectAWSRegion": {
> "Fn::Not": [
> {
> "Condition": "CorrectAWSRegion"
> }
> ]
> }
> },
> "Resources": {
> "S3Bucket": {
> "Type": "AWS::S3::Bucket",
> "Condition": "CorrectAWSRegion",
> "Properties": {
> 
> ```
>         }
>     },
>     "DynamoDBtable": {
>             "Type" : "AWS::DynamoDB::Table",
>         "Condition": "CorrectAWSRegion",
>             "Properties" : {
>                 "AttributeDefinitions" : [
>                   {
>                     "AttributeName" : "userId",
>                     "AttributeType" : "S"   
>                   }
>                 ],
>               "KeySchema" : 
>                   [
>                       {
>                         "AttributeName" : "userId",
>                         "KeyType" : "HASH"
>                       }
>                   ]
>                 
>                 ,
>               "ProvisionedThroughput" : {
>                 "ReadCapacityUnits" : 5,
>                 "WriteCapacityUnits" : 5
>               },
>               "TableName": "AlexaAssistantSkillSettings"                       
>             }
>         
>     },
>     "LambdaFunctionRole": {
>         "Type": "AWS::IAM::Role",
>         "Condition": "CorrectAWSRegion",
>         "Properties": {
>             "AssumeRolePolicyDocument": {
>                 "Version": "2012-10-17",
>                 "Statement": [
>                     {
>                         "Effect": "Allow",
>                         "Principal": {
>                             "Service": [
>                                 "lambda.amazonaws.com"
>                             ]
>                         },
>                         "Action": [
>                             "sts:AssumeRole"
>                         ]
>                     }
>                 ]
>             },
>             "Path": "/",
>             "Policies": [
>                 {
>                     "PolicyName": "GoogleAssistantPolicy",
>                     "PolicyDocument": {
>                         "Version": "2012-10-17",
>                         "Statement": [
>                             {
>                                 "Sid": "AllowLogging",
>                                 "Effect": "Allow",
>                                 "Action": [
>                                     "logs:CreateLogGroup",
>                                     "logs:CreateLogStream",
>                                     "logs:PutLogEvents"
>                                 ],
>                                 "Resource": [
>                                     "*"
>                                 ]
>                             },
>                             {
>                                 "Effect": "Allow",
>                                 "Action": "s3:*",
>                                 "Resource": [
>                                     {
>                                         "Fn::Join": [
>                                             "",
>                                             [
>                                                 {
>                                                     "Fn::GetAtt": [
>                                                         "S3Bucket",
>                                                         "Arn"
>                                                     ]
>                                                 },
>                                                 "*"
>                                             ]
>                                         ]
>                                     }
>                                 ]
>                             },
>                             {
>                                 "Effect": "Allow",
>                                 "Action": "dynamodb:*",
>                                 "Resource": [
>                                     {
>                                         "Fn::Join": [
>                                             "",
>                                             [
>                                                 {
>                                                     "Fn::GetAtt": [
>                                                         "DynamoDBtable",
>                                                         "Arn"
>                                                     ]
>                                                 },
>                                                 "*"
>                                             ]
>                                         ]
>                                     }
>                                 ]
>                             }
>                             
>                         ]
>                     }
>                 }
>             ]
>         }
>     },
>     "AlexaSkillFunction": {
>         "Type": "AWS::Lambda::Function",
>         "Condition": "CorrectAWSRegion",
>         "Properties": {
>             "FunctionName": "alexa-assistant-skill-function",
>             "Handler": "index.handler",
>             "Role": {
>                 "Fn::GetAtt": [
>                     "LambdaFunctionRole",
>                     "Arn"
>                 ]
>             },
>             "Description": "Alexa Skill code for the Google Assistant Skill",
>             "Code": {
>                 "S3Bucket": {
>                     "Fn::FindInMap": [
>                         "RegionMap",
>                         {
>                             "Ref": "AWS::Region"
>                         },
>                         "BUCKET"
>                     ]
>                 },
>                 "S3Key": "index_1.2.zip"
>             },
>             "Runtime": "nodejs10.x",
>             "Timeout": "10",
>             "MemorySize": "1344",
>             "Environment": {
>                 "Variables": {
>                     "S3_BUCKET": {
>                         "Ref": "S3Bucket"
>                     },
>                     "API_ENDPOINT": "embeddedassistant.googleapis.com"
>                 }
>             }
>         }
>     },
>     "AlexaSkillFunctionPermissions": {
>         "Type": "AWS::Lambda::Permission",
>         "Condition": "CorrectAWSRegion",
>         "Properties": {
>             "FunctionName": {
>                 "Ref": "AlexaSkillFunction"
>             },
>             "Action": "lambda:InvokeFunction",
>             "Principal": "alexa-appkit.amazon.com"
>         }
>     }
> },
> "Outputs": {
>     "FunctionARN": {
>         "Condition": "CorrectAWSRegion",
>         "Value": {
>             "Fn::GetAtt": [
>                 "AlexaSkillFunction",
>                 "Arn"
>             ]
>         },
>         "Description": "Lambda function ARN to be placed in the Amazon Developer Portal"
>     },
>     "FunctionError": {
>         "Condition": "IncorrectAWSRegion",
>         "Value": "Incorrect AWS Region!!! Must be US-East(N. VIRGINIA) or EU(Ireland)",
>         "Description": "You must Select US-EAST (North Virgina) if you are located in North America or EU (Ireland) if you are located elsewhere"
>     }
> }
> ```
> 
> }

thanks no luck :(..but why is it uploading so large ..its just one file lol..one last thing , does your function part look like this ?
![shnd](https://user-images.githubusercontent.com/18756975/98457988-6f22df00-2162-11eb-8431-be8a160770fa.png)

**Comment by Iangh59** [comment]
Yes, it did say that.

I reckon I got it working on the 5th go when I started from scratch and went very slow as it was obvious, given others had it working, I was doing something wrong. Take a rest and try again tomorrow.  Print the instructions and tick off as you go along. Reboot Echo. Enabling the skill involves giving permission to Amazon.co.jp.

**Comment by trinib** [comment]
> 
> 
> Yes, it did say that.
> 
> I reckon I got it working on the 5th go when I started from scratch and went very slow as it was obvious, given others had it working, I was doing something wrong. Take a rest and try again tomorrow. Print the instructions and tick off as you go along. Reboot Echo. Enabling the skill involves giving permission to Amazon.co.jp.

yayy working now :) i did not know zip uploaded to function although it looked like it didnt lol
