### ISSUE TITLE
"POLLY_VOICE" Environment variable doesn't do anything

### ISSUE THREAD

**Issue by Jademalo** [tartanguru/alexa-assistant#12]
I'm not exactly sure what this variable is changing. If I say "Alexa, open Google", then it's a female british voice that says "How may I help" no matter what I have the variable set to. After asking the question, the response is a female american voice that I'm assuming is the default google voice.

What exactly is the polly voice synth used for, and how can I tell if the environment variable is actually changing the voice?

**Comment by daniel-stoneuk** [comment]
The Polly voice is converting the text that Amazon sends the skill into
speech which is then fed into the Google Assistant API, you don't get to
hear it & Polly seems to be the best voice.

>

**Comment by Jademalo** [comment]
Aaaah, that makes a lot more sense.
Thanks!
