### ISSUE TITLE
German language support

### ISSUE THREAD

**Issue by daniel-lo** [tartanguru/alexa-assistant#17]
It sais it doesn't support German and it really doesn't ;-) Any plans on adding this? Should I use the older unsuported version? Any advice is appreciated. Cheers

**Comment by tartanguru** [comment]
The Google Assistant API only works with US English at the moment.
As soon as Google support more languages then I will support them

**Comment by daniel-lo** [comment]
Thanks! In the mean time would you recommend to use the old skill you provided?

**Comment by tartanguru** [comment]
There's no reason not too, but I won't be supporting it any more if it
stops working!

**Comment by FWeissenb** [comment]
https://developers.googleblog.com/2017/10/apps-for-google-assistant-new-languages.html

Is there any change needed? Or is it possible to add it as german skill and it works?

**Comment by tartanguru** [comment]
The Assistant API for third parties still only supports US English

**Comment by daniel-lo** [comment]
Hi, is there any news on this topic. I recall having read that languages other than English are supported now.

**Comment by tartanguru** [comment]
See issue 26

**Comment by daniel-lo** [comment]
Good to see there is progress .. thanks. Not being too tech .. I guess I'll rather wait for non beta stage. Regards.
