### ISSUE TITLE
Host index.zip on s3?

### ISSUE THREAD

**Issue by StudioLE** [tartanguru/alexa-assistant#20]
Uploading the `index.zip` file to create the Lambda functions is a significant bottleneck to the process, especially for those of us with inferior upload connection speeds. 

This could be avoided if the `index.zip` file were hosted on a publicly accessible s3 bucket. Users would then select "Upload a file from Amazon S3" and paste in the S3 link URL rather than manually downloading the file from GitHub only to re-upload it.

**Comment by JZ-SmartThings** [comment]
Are you prevented from pasting the GitHub URL to the ZIP file which is kept up to date on the root of this repo: https://github.com/tartanguru/alexa-assistant/raw/master/index.zip

**Comment by StudioLE** [comment]
Using anything but an S3 URL results in the error: `Must be a valid S3 URL, e.g. https://s3.amazonaws.com/bucket/path.`

**Comment by tartanguru** [comment]
Great idea however I there would be costs too myself for hosting the file and also the S3 bandwidth charges. Given how popular the skill is and the size of the download this would cost me a not insignificant amount, so I'm not willing to do this I'm afraid. 

Unfortunately Lambda only supports S3 link and not dropbox

**Comment by JZ-SmartThings** [comment]
Sorry just checked, upload and S3 link are the only options. I guess they did that for security.
