### ISSUE TITLE
 Alexa google skill

### ISSUE THREAD

**Issue by Juno1111** [tartanguru/alexa-assistant#22]
[SEARCH.txt](https://github.com/tartanguru/alexa-assistant/files/1188482/SEARCH.txt)
[LICENSE.txt](https://github.com/tartanguru/alexa-assistant/files/1188486/LICENSE.txt)
google skill

**Comment by Juno1111** [comment]
![skill_information](https://user-images.githubusercontent.com/30394987/28792459-f778cf36-762f-11e7-850d-877e648268ef.jpeg)

**Comment by Juno1111** [comment]
![add_new_skill](https://user-images.githubusercontent.com/30394987/28792524-39236496-7630-11e7-9258-d13e1a3ff49e.jpeg)

**Comment by Juno1111** [comment]
![authorise](https://user-images.githubusercontent.com/30394987/28792543-46e65caa-7630-11e7-941c-a1cccecfe11c.jpeg)

**Comment by tartanguru** [comment]
I'm sorry but I don't understand what it is that you are raising here?

**Comment by tartanguru** [comment]
Closing as there has been no further correspondence
