### ISSUE TITLE
No prompt to link google to Alexa

### ISSUE THREAD

**Issue by mcshu** [tartanguru/alexa-assistant#25]
I have gotten to the section "Linking the skill to your Google Account"
When I do step 3 "Alexa, open google", Alexa responds "I couldn't find any enabled video skills" and tells me to go to the Music, Video and Books section of the Alexa app and enable a video skill. I do have a fire tv so I linked that to my Echo.  Now when I say "Alexa open google", Alexa responds "Getting google from firetv"  
I do not get a prompt to link my account through the Alexa app. (step 5).

What am I missing?

Thanks,
Teresa McBennett

**Comment by tartanguru** [comment]
Please try the command "Alexa ask google what is the time?" and see if it
does the same?

**Comment by mcshu** [comment]
She says "Sorry something went wrong"

**Comment by tartanguru** [comment]
Is the app showing in the my skills section of the Alexa app?
If so try linking the account from there

**Comment by mcshu** [comment]
The app does not show up in the Skills section of the Alexa app.

**Comment by dahauss** [comment]
If it doesnt show up, then its not linked to your account.  When I go to MY ALEXA SKILLS I see "Google Assistant for Alexa"

**Comment by tartanguru** [comment]
Have you signed up to the Amazon developer portal using the SAME email address as the Amazon account that the echo is linked to? Is the skill enabled for testing on your account (see the testing tab on the skill setup)?

**Comment by mcshu** [comment]
I have used the same email address for both accounts.

I'm not sure I am in the right place to answer the second question as I do
not see a testing tab.  I am here
https://developer.amazon.com/edw/home.html#/skills

and the Google Assistant or Alexa is listed and says the status is
Development.

Would it be easier for me to just start over?  If so, how do I get rid of
what I have created so far?

**Comment by tartanguru** [comment]
Retrace your steps using the video guide here:-

https://www.youtube.com/watch?v=2KzbJyTQTZE&t=238s

That's all I can really advise.

**Comment by mcshu** [comment]
Thanks so much for your help.  I will retrace these steps and hope it works.

Would be so great!

Teresa McBennett

**Comment by savioesse** [comment]
Hi, great skill.
It all worked fine at the end to me, but now is asking me to link my account to google. I do that, but it works only temporary

**Comment by tartanguru** [comment]
Please look at Known Issue number 2 as this covers this problem
