### ISSUE TITLE
It´s is not working in Germany (with english language), what is my problem/error

### ISSUE THREAD

**Issue by StripLV** [tartanguru/alexa-assistant#29]
Hello tartanguru,
I am writing to you from Germany.
First of all thanks for your work! 

I have tried this Skill and I have problems to get this working. 
I am at the last point:

-Launch the Google skill by asking "Alexa, open google" (or whatever invocation name you gave e.g "my assistant"
-The skill will tell you if you have forgotten to set any environment variables or if there any other set-up issues
-You will then be prompted to link your account through the Alexa app.

That did not work. I tried then to link the google account through the Alexa App. That worked but I still can´t rather/fairly use it.

When I say 
"Alexa, starte google" (starte is the german word for start)
"Alexa öffne google (öffne is the german word for open)
"Alexa open google"
"Alexa start google"
then the "blue LED ring" is "blinking" for ca. 1 Sek. and I get now answer OR  she says (in german) "I can´t find this skill

I tried then to ask her 
"Alexa open google how old is Donald Trump"
"Alexa öffne google how old is Donald Trump"
"Alexa ask google how old is Donald Trump"

But it´s not working. Why is that?
I thought when I ask her in english she wouldt also answer me in english.
Is there no way to get this working, even if I talk to Alexa in english language and she also answer me in english or is there ANY way to your skill working?

Thanks A LOT in advance!
Kind Regards,
Dennie

**Comment by tartanguru** [comment]
Have you set up the skill as German as it's language? Otherwise your device
won't be able to see the skill

**Comment by StripLV** [comment]
In the Skill I did choose "English (UK)" because everywhere stands that German will not work.
Do I know have to delete everything and make everything new or can I "add a new language"?
If I can "add a new language" is it then possible to set this as "standard" and delete the english?

**Comment by tartanguru** [comment]
Just add German as an additional language - no need to delete the english
version

**Comment by StripLV** [comment]
I did add German. Now it is working but in GERMAN. I can ask Alexa in German and she answers me also in German. I thougt this is not possible? Or is this now the same function as your "old" skill? I mean now I do not have all the functions of the Assistant Skill, but the same as your old skill?

Can you please explain that a little bit to me?
THANKS!

**Comment by tartanguru** [comment]
Are you sure you have uploaded the correct zip file? It sounds like you might have uploaded the old google skill as the new one will answer with the Google Assistant voice (not Alexa's) and will be American English

**Comment by StripLV** [comment]
Yes, I am. I uploaded it again and now it works. THANKS!
