### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by digiltd** [tartanguru/alexa-assistant#3]
Hi, saw your post on Reddit. 

Quick question, is there any reason you have included the node_modules folder rather than a package.json? Did you make any changes to files in the dependencies or is it ok to `npm init` what you have done? (below is what npm init gave me)

```json
{
  "name": "alexa-assistant",
  "version": "1.0.0",
  "description": "Implementation of the Google Assistant API for Alexa",
  "main": "index.js",
  "dependencies": {
    "alexa-sdk": "^1.0.9",
    "every-moment": "^0.0.1",
    "googleapis": "^19.0.0",
    "grpc": "^1.1.2",
    "lame": "^1.2.4",
    "pcm-volume": "^1.0.0",
    "resolve": "^1.3.3",
    "stream": "^0.0.2",
    "wait-one-moment": "^0.0.2"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/tartanguru/alexa-assistant.git"
  },
  "author": "tartanguru",
  "license": "GNU",
  "bugs": {
    "url": "https://github.com/tartanguru/alexa-assistant"
  },
  "homepage": "https://github.com/tartanguru/alexa-assistant"
}

``` 

When running `npm install` the node_modules folder from your repo is 68.2mb, the one created using the package.json file 107mb.

**Comment by tartanguru** [comment]
Hi this was a conscious decision to make the package as easy to deploy as possible.

There are a lot of native binaries including gprc and LAME. These have to be built on an Amazon Linux machine in order for them to run in a Lambda function. Including them in the release ensures that the right binaries are present to deploy. 
Additionally, as you spotted, the node_modules created by npm is pretty big which results in upload times to AWS of over 2 minutes which was slowing down development. A lot of this is from gprc and the Google API's so I stripped these down to the bare minimum for the Skill to run

**Comment by tartanguru** [comment]
So I think the answer is yes - you can npm init, but if you want it to actually work then you'll have to do it on an EC2 instance!
