### ISSUE TITLE
Dynamo Permission in IAM role?

### ISSUE THREAD

**Issue by itopiacloud** [tartanguru/alexa-assistant#31]
I took a look in my eu-west-1 region (Ireland) but can't see any dynamoDB tables listed -- what's the need for the dynamoDB permission in the role policy?

**Comment by tartanguru** [comment]
The intention was to use dynamoDB to store a users settings to allow
multi-tenancy on the skill.
Unfortunately there was a bug in the Alexa SDK at the time of publishing so
this feature was removed just be public release.
The permissions for DynamoDB have been left in to support this feature in a
future upgrade, as this will allow existing users to just upload a new zip
file
