### ISSUE TITLE
file to big

### ISSUE THREAD

**Issue by stefi01** [tartanguru/alexa-assistant#33]
every time i try put an s3 link in to the upload file from s3 link  it always says the same thing
The deployment package of your Lambda function "google-assistant" is too large to enable inline code editing. However, you can still invoke your function right now.

i get the same when i try upload the index.zip file, internet should be up for it, its fiber.

getting to the stage of giving up

**Comment by tartanguru** [comment]
Hi,

That's not an error it is a warning.
You do not need to worry about it and just carry on with the next steps
