### ISSUE TITLE
AWS Console UI has changed, instructions are out of date

### ISSUE THREAD

**Issue by mturley** [tartanguru/alexa-assistant#35]
I was setting this up and noticed that the AWS Console has changed significantly enough that the setup instructions in the README should be updated.  The order of the steps has changed, things are in different places and now it's important to scroll back up and click the Save button which was easy for me to miss.

I'm adding this issue to let you know that I'm already on it-- don't bother taking new screenshots because I just did so while I was doing my own setup. I will post a PR including my updates to the instructions and screenshots later today (I should get back to work first).

New stuff that justifies the update includes this new visualization they added:
![screen shot 2017-12-01 at 1 52 55 pm](https://user-images.githubusercontent.com/811963/33498357-0452b09e-d69f-11e7-8c67-247c72e9e542.png)

Feel free to assign me @mturley on this issue if you like.

**Comment by asantaga** [comment]
Nice, yes I noticed it had also changed...

**Comment by Fenton-Fenton-Fenton** [comment]
Hi thanks for saying that you are going to update this.

**Comment by mturley** [comment]
Thanks for the reminder, I forgot to put up my screenshots. I’ll see if I
have time today, otherwise I’ll put it up after Xmas.

**Comment by tartanguru** [comment]
Hi Mike,

No rush - I’m actually working on a new release to support the updated API,
but it would save me a massive piece of work not to have to redo all of the
screenshots

Have a good Christmas

Ross

**Comment by mturley** [comment]
Hi Ross,

No worries.  I haven’t found a free moment with holiday family stuff going
on, but I already took all the new screenshots. Just need to update the
README. If I haven’t put up a PR by New Year’s feel free to remind me.

- Mike

**Comment by drizzt09** [comment]
doesnt appear to be a "blank" blueprint option either

**Comment by tartanguru** [comment]
Hi Mike,

Just giving you a nudge!

Ross

**Comment by tartanguru** [comment]
I am moving to a CloudFormation based deploy for the new version which will be simplier. It will also mean that the current instructions do not need updating as they will be redundant

**Comment by mturley** [comment]
Oh, really? Ha! I had just gotten my branch together with the new screenshots. Any value in pushing them anyway in the meantime, or are you about ready to move to CloudFormation?

**Comment by mturley** [comment]
Sorry for the delay on this originally. Holidays got crazy and then work got crazy after that.
