### ISSUE TITLE
OAuth with Google stopped working Yesterday?

### ISSUE THREAD

**Issue by Taconut** [tartanguru/alexa-assistant#36]
Hi! I've been using this skill since late last November, and it's been super helpful! Being able to use both Alexa-exclusive and Assistant-exclusive commands has been amazing!

However, since last night the skill hasn't been working. When I ask Google something through my echo, Alexa says "I wasn't able to talk to Google - please try again". When I check the Lambda logs, there's a line that says

```
***There was a Google error**Error: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
```

It seems like alexa-assistant _does_ see the credential, though. Whenever I make a request to the google assistant, there's a little spike in my Google Cloud Platform traffic log.

This issue is really stumping me. Have any ideas what might be causing it?

Thanks a bunch for your amazing skill, 

Alex Hulbert

**Comment by ErikJohnRichter** [comment]
+1!!! I am seeing the EXACT same thing!! I am getting "I wasn't able to talk to Google. Please try again." Per your recommendations below, I have double checked that my API_ENDPOINT is embeddedassistant.googleapis.com, and it is, with no extra spaces. My invocation is "Alexa, ask google how many calories are in a hotdog." ...from which I get the "wasn't able to talk to Google" answer. If I say "Alexa, open Google," she says, "How may I help?" I just cannot ask a question and get a response. Also, on a positive note, I am seeing the request pings show up on my Google API dashboard graphs. Any other thoughts?

**Comment by tartanguru** [comment]
The OAuth authentication is all dealt with by the Alexa SDK. Google have just blocked Amazon from using YouTube on the Echo Show, so it might be that they are blocking Amazon skill from using it too. I’ll investigate

**Comment by ErikJohnRichter** [comment]
Thanks!

**Comment by tartanguru** [comment]
Looks like this isn't anything sinister - other users of the API are reporting issues and a Google employee has confirmed there is an issue here:-

https://plus.google.com/114306113999433581153/posts/Rfy4bJ7F8sy

**Comment by gpitts1981** [comment]
thanks for the heads up, I work in a service center that has to keep up wityh tech news like google blocking the echo show from accessing youtube, so when i got home and alexa-assistant said she couldnt communicate with google i thought it was due to them blocking aws from accessing the assistant-api. glad thats not the case and hopefully it will be up and running again soon.

**Comment by tartanguru** [comment]
Google have confirmed an issue with the SDK that the skill uses and say that they are rolling out a fix:-
https://github.com/googlesamples/assistant-sdk-python/issues/138

**Comment by tartanguru** [comment]
Google have fixed the issue and the skill is working again for me

**Comment by Taconut** [comment]
Yup! Everything's back in order again. Thanks again for this amazing skill!
