### ISSUE TITLE
S3 Bucket issue

### ISSUE THREAD

**Issue by jranjansingh** [tartanguru/alexa-assistant#37]
When I say Alexa, ask google or Alexa, open google. Alexa says ERROR! S3 Bucket Name is not set in Lambda Environment Variables

Please help, i have tried random string again and upload of zip file but no luck.

**Comment by tartanguru** [comment]
Before you go any further I must warn you that you may also find that the
skill won't work any more as Google seem to be blocking the authentication
in the past few days

If you do wish to continue, are you sure you have the environment variables
named EXACTLY as per the instructions i.e. S3_BUCKET with no spaces before
or after?

**Comment by jranjansingh** [comment]
Thank you so much for your quick response, much appreciated.

I had bucket in small letters so that is fixed, now when i go to link account in alexa app it gives me error

The redirect URI in the request, https://layla.amazon.com/api/skill/link/xxxxxxxxxxxxxx, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/xxxxxxxxxxxxxxx-xxxxxxxxxxxxxxx.apps.googleusercontent.com?project=xxxxxxxxxxxxxxxxxx to update the authorized redirect URIs.

**Comment by tartanguru** [comment]
Have you replaced the xxxxxxxxxxxx's with the actual values from your skill
setup?

I'm going to repeat that the skill probably won't work at the moment!

**Comment by jranjansingh** [comment]
Yes, I have replaced xxxxxx, another thing i don tunderstand is when am in UK why is this taking the layla link instead of "https://pitangui.amazon.com/api/skill/link"

also as you mentioned Google is blocking i just want to make sure block is from google and problem is not in my configuration.

Thank you so much again.

**Comment by tartanguru** [comment]
To be honest - it doesn't really make a massive difference which one you
use part from a bit of latency.
Try the other one as see it makes any difference.

Did you add both of the redirect URL's to the google API manager?

**Comment by jranjansingh** [comment]
Yes, I added bothURL's to the google API Manager. 

One thing i wanted to mention, in Google API manager i don't see the xxxxx part of this URL : https://layla.amazon.com/api/skill/link/xxxxxxxxxxxxxx,

I got the URL with xxxx from Alexa Skill setup page. Is that the right place to pick. I delete and recreated the skill but the xxxx part remained same.

**Comment by tartanguru** [comment]
You definately need the xxxxxxxxxx part of the URL entered into the API
manager. It's present when I Iook at my API manager

**Comment by jranjansingh** [comment]
all done, thank you so much for your quick responses and patience. It was error from my side. Thanks once again for the brilliant article.

**Comment by jranjansingh** [comment]
clearly, i was too excited. everything is configured but it says "I wasn't able to talk to Google - please try again"

I have doube checked embeddedassistant.googleapis.com and cerated English US and English UK as well, still no luck. Sorry for being pain.....

**Comment by tartanguru** [comment]
That is the issue I was talking about earlier. Google seem to have
acknowledged this is a problem at their end. Hopefully they will fix it soon

**Comment by tartanguru** [comment]
Google have fixed the issue and the skill should be working again

**Comment by jranjansingh** [comment]
thanks for the update, now Alexa says "give me permission to help you" for anything I ask. I have tried Disable Skill, Enable Skill and then link account.

**Comment by tartanguru** [comment]
This problem is covered in the known issues
