### ISSUE TITLE
Storing conversational context

### ISSUE THREAD

**Issue by chriotte** [tartanguru/alexa-assistant#38]
One thing that makes Google Assistant great is its ability to understand the context of the conversation.  So for example, if I ask:
**What is the weather like?**
Google will reply with the weather of my location
**How about tomorrow?**
Google will understand that I'm still asking about the weather. 

Unfortunately, this is not working through the Alexa webhook, and I can't find any documentation about how a context parameter can be passed to the Assistant API, but I would assume its possible as DialogFlow supports a context parameter in the request.
So if the assistant can take a context parameter, we can store the context temporarily in a database and send it in if the user queries google within a short timespan again.

**Comment by tartanguru** [comment]
Hi,

The skill already supports this and maintains the context across dialogues.
I have just tired the conversation you have outlined and it works perfectly
for me with it remembering that I am talking about my home location.

**Comment by chriotte** [comment]
Hi,
Thank you for the prompt reply! I think there might be a minor misunderstanding, it remembers the home location because it's saved in the connected Google account, but it can't remember what topic we were talking about across invocations (context). 

When I ask Google what the weather is like, she tells me the weather in my home location London, and the Echo goes back to standby.
Then I again do 'Alexa ask google how about tomorrow', but she has forgotten that we were talking about the weather.

**Comment by chriotte** [comment]
A simple way of changing this is to not close the session with Google when the answer comes back, this will at least let us query google twice.

**Comment by tartanguru** [comment]
The skill follows the Google Assistant API specification. The API asks you
to close the session if the
ConverseResponse.result.microphone_mode.DIALOG_FOLLOW_ON
which is missing from the response which it is if you are just asking for
the weather.
The skill does however keep the conversation_state token from the Google
API for the duration of the skill remaining active on lambda which is
usually an hour or so and I have not had any other reports of the context
not being maintained between questions a few minutes apart.

I have repeated the test again and the Google Assistant is indeed able to
maintain the context:-

Alexa ask google what is the weather for tomorrow:-

Answer - in XXXX the weather will be ......

Alexa ask google how about tomorrow?

Answer - there will be showers tomorrow in XXXXXX and it will be 2 degrees


When the API is out of beta then I will support multiple users and will
thus store the conversation.state token between skill invocatuon session

**Comment by chriotte** [comment]
Thank you tartanguru for the detailed answer! For some reason, the context is not saved for me when the microphone is turned off and the session is closed after asking about the weather, I then redo the command 'Alexa, ask google about tomorrow' and google answers 'Hold on, what did you want to know?'.

But, as its working for you and if the conversation_state is saved I'll have a look at my Lambda and skill configuration to see where the problem is at my end.
Thank you for your time and great effort into making this work! 
I'm closing the issue now.

**Comment by tartanguru** [comment]
It does sound like your lambda function is being terminated early - this
usually happens if it is using too much memory. Trying adjusting it's
memory allocation

**Comment by chriotte** [comment]
Thank you, it worked!  I had it deployed through serverless and the memory size was set to 512 and not 1536
