### ISSUE TITLE
Request: Heroku support

### ISSUE THREAD

**Issue by drizzt09** [tartanguru/alexa-assistant#39]
I got the kodi skill working with using the Heroku setup option from https://github.com/m0ngr31/kodi-alexa
because I couldnt get the AWS version setup (no Credit Card)
Would be awesome if you could get this skill working through Heroku as well. Thanks

**Comment by tartanguru** [comment]
Hi,

Sorry but I don't use Heroko so I'm not in a position to be supporting it,
but perhaps someone else may be kind enough to fork it to support the
platform
