### ISSUE TITLE
Alexa says "Sorry, something went wrong"

### ISSUE THREAD

**Issue by cinergi2** [tartanguru/alexa-assistant#40]
Followed all the configuration instructions.  When I say "Alexa, open Google" as instructed near the end, it just says "Sorry, something went wrong" (LOL, not very helpful).  Neither Amazon nor Google show any invocations.  Not sure where to start troubleshooting.

Thanks
cinergi

**Comment by tartanguru** [comment]
There could be many issues here:-

1. Is the echo on the same account that you set the skill up on
2. Are the skill and device set to the same language
3. Are you sure you have added the Alexa skill kit as a trigger

**Comment by cinergi2** [comment]
Thanks, the problem was #2: My Echo device is set to English (Canada) but I created the Skill using English (US).  I recreated the skill using English (Canada) and it works fine now.  Thanks for your help!

cinergi

**Comment by AnayaDic** [comment]
Facing same issues when Alexa say something went wrong but I find this problem what is the reason when Alexa say something went wrong- 
1. Sometimes weak internet connection cause problem
2. Bluetooth Connectivity Issues
3. Alexa can't recognize voice
And other issues. I solve this issue by troubleshooting Wi-Fi connection such as 
1. You can turn your device on and off again for few seconds.
2. Check your Amazon device is registered to your Amazon account.
3. Look for the name you've given your Amazon device
4. Connect the device to 2.4GHz network on the router.
5. Restart the Alexa device.
I followed [Amazon Alexa Customer Support](https://echoalexasupport.com/echo-setup-troubleshoot/) instructions and get free resolutions for Alexa issues.

**Comment by AnayaDic** [comment]
Facing same issues when Alexa say something went wrong but I find this problem what is the reason when Alexa say something went wrong- 
1. Sometimes weak internet connection cause problem
2. Bluetooth Connectivity Issues
3. Alexa can't recognize voice
And other issues. I solve this issue by troubleshooting Wi-Fi connection such as 
•	You can turn your device on and off again for few seconds.
•	Check your Amazon device is registered to your Amazon account.
•	Look for the name you've given your Amazon device
•	Connect the device to 2.4GHz network on the router.
•	Restart the Alexa device.
I followed [Amazon Alexa Customer Support](https://echoalexasupport.com/echo-setup-troubleshoot/) instructions and get free resolutions for Alexa issues.

**Comment by tartanguru** [comment]
Have you looked at the points in my response to cinergi2?

**Comment by holyslayerpt** [comment]
If i say "alexa, ask google to turn on my tv" i get an error message saying "sorry something went wrong". But if i say "alexa, ask google" and then, after the skill appears on my echo screen i say "turn on my tv" then it works. Is this normal ?
