### ISSUE TITLE
Collaborate with Steve Gattuso to make an Assistant/Google Music unified Skill !

### ISSUE THREAD

**Issue by brunes007** [tartanguru/alexa-assistant#41]
Steve Gattuso has created an Alexa Skill that allows you to play Google Play Music on Alexa - https://github.com/stevenleeg/geemusic

I have both his skill and yours installed, and they both work flawlessly. The only pain is I have to call one "Google" and the other "Google Music", so I have two different "Ask" commands.

It would be really stellar to just have one skill. I am pretty sure these could be unified. The main difference in the code bases is you are using Lamdas, whereas he has his Node app running in a Heroku server or Docker container. From reviewing the code, I am quite sure that his could be easily ported to Lamdas, as it's all node and appears quite stateless.

**Comment by tartanguru** [comment]
Hi,

I appreciate why this would be great however it isn’t a direction that I
will be taking the skill for a few reasons:-

1. The intention of the skill was just to provide access to Google Assistant
2. My skill is written in Node.js whilst the GeeMusic skill is in python
which I have no knowledge of so this would be a very big task. The existing
skill has already taken many weeks of my time to develop
3. I’m not a Google Music user and have no intention to be one
4. It is likely that Google will add Google Music support to the Assistant
anyway - if they do then I would add generic music playback support.
5. I’m UK based and many of the Music Slot intents aren’t available here

If there is a big demand for this then I’m sure someone in the community
can fork the code bases and create a combined skill

Ross
