### ISSUE TITLE
Instructions for Release 2-1 need updating?

### ISSUE THREAD

**Issue by snipah** [tartanguru/alexa-assistant#45]
Thanks for your great job. I understood that you took a different approach for Release 2-1 and got rid of the index.zip-file, but I guess you are not finished yet and the instructions will be updated once you're done?

**Comment by rkm82** [comment]
subscribing

**Comment by tartanguru** [comment]
Hi,

Please watch the main release branch and you will be notified when the
project is updated and released
Github branches are normally used for development so it isn't usually
expected to raise issues against them as they are frequently updated and
could be very broken!
When the work is completed then they will be merged into the main trunk.

Thanks

**Comment by tartanguru** [comment]
Hi,

The instructions for deploying the new version of the skill have been moved to a separate project here:- 
https://github.com/tartanguru/alexa-assistant-instructions

The reason for this is to allow them to be licensed under the Attribution-NonCommercial-NoDerivatives 4.0 International license and prevent other sites from monetising the instructions as I know host the files as a CloudFormation template and have to pay for this
