### ISSUE TITLE
Sorry to ask for help...

### ISSUE THREAD

**Issue by AlanHos** [tartanguru/alexa-assistant#48]
![alexa unable to link to google](https://user-images.githubusercontent.com/36554346/36335342-34e8541a-1377-11e8-9b54-79c881b243f2.PNG)

I'm getting the error "We were unable to link Google Assistant for Alexa at this time."  after following your instructions https://skills-store.amazon.com/external/link-result?success=false&languageCode=en_US&skillId=amzn1.ask.skill.84fbc648-15a0-4673-b1e8-245271db666c&skillStage=development.

Is this a change in the link service?  If not, where do I go to fix?

Respectfully,
Alan Hoshor
alan@watercascades.com

**Comment by tartanguru** [comment]
This is usually an issue with the skillauthentication settings.
Double check you have pasted the client secret/ID, authorisation and
re-direct URL’s into the correct fields and that you don’t have any extra
spaces before or after any of them

**Comment by AlanHos** [comment]
Greetings Tartanguru,

I tried again this morning and linking worked.  Apparently something was down at Google.  Thanks for your gift of this code.  I'm so excited to use it now!

Cheers,
Alan
