### ISSUE TITLE
Enable repeated requests

### ISSUE THREAD

**Issue by HighIander** [tartanguru/alexa-assistant#49]
Hi,

since the google assistant allows to continue a query after its response, i.e. to conduct kind of a natural conversation, it would be quite fancy if this would be possible with Alexa, too.
This means that the skill should not quit after it read the answer of the google assistant, but rather listen for a second (and third...) request by the user. Thus, this would enable an interaction in the fashion as "Alexa, ask google how old is Trump."... google answers ... "and when was he elected as president?" ... google reads this answer ... [and so on].
I recognize, that it might be confusing for some users when they in fact only want to have one simple answer, but maybe one could simply set up a second skill with the trigger word "google conversation". So to get a single answer you could say "Alexa, ask google how old is Trump", and for the conversation "Alexa, start a google conversation, how old is Trump? ... And when was he elected? ... ... ... "?

In any case, I love this project, keep on the good work for all users [in fact mankind, as I believe that the unification of services is the key to serve users best]!

HighIander

**Comment by tartanguru** [comment]
Hi,

That’s a good suggestion - in fact one of the development branches of my
earlier Google search skill included this functionality before I abandoned
it when the Assistant API became available
The easiest way of implementing this would to just look for the command
“Alexa - ask Google to start a conversation”.
The skill would then leave the microphone open after a response.

I’ll try an include this in an update

Regards

Ross

**Comment by FrattYoung** [comment]
FYI, Follow-up Mode is now available for Alexa. You have to manually enable the feature in Settings for each device. 

Thanks for sharing this awesome skill.

**Comment by tartanguru** [comment]
US only feature at the moment so I’m unable to confirm
