### ISSUE TITLE
Idea: Alexa app card

### ISSUE THREAD

**Issue by daniel-stoneuk** [tartanguru/alexa-assistant#5]
I like to see what Alexa hears and responds in the Alexa app, it would be awesome if the skill could create a card in the app [using the API](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/providing-home-cards-for-the-amazon-alexa-app).

The title could be the request sent to Google Assistant and the content could be `spoken_request_text` extracted for the `ConverseResponse` [documented here](https://developers.google.com/assistant/sdk/prototype/getting-started-other-platforms/integrate) if that's possible.

Awesome skill by the way, I can see myself using it loads!

**Comment by tartanguru** [comment]
Hi, 

That feature is already implemented as an optional setting - see the additional environment settings section at the bottom of the readme

**Comment by daniel-stoneuk** [comment]
Yeah, I saw that before though it's not exactly pretty - a nice looking card would be good. I'll try making one now just to see what it'll be like.

**Comment by tartanguru** [comment]
The reason why I haven't implemented a card by default is that you don't really know whether the response from the Google assistant it going to be useful or not and you run the risk of filling your Alexa app with needless information cards if you are engaging in a long conversation.

The information you need is already in the debug card so I guess you could just reformat what is already there to make it look nice (although you might want to ignore STOP, CANCEL and EXIT commands). If you want to add an image then you could easily host that in the skills S3 bucket as a publicly accessible image

**Comment by daniel-stoneuk** [comment]
![image](https://user-images.githubusercontent.com/15860949/27087007-c4c03458-504b-11e7-80a0-6cf1a1de4c69.png)


Ah so that's what it means. Looks like it won't be possible then until they update the API to respond with text for anything other than IFTTT.

Looks like it's a recognised request: https://plus.google.com/101852559274654726533/posts/BskrFscRYdh

Leave this open if you'd like, for now the cleaner card without response is enough for me (won't pr since it's quite simple)

**Comment by tartanguru** [comment]
Yes the only text that you get back (other than an IFTTT response which I haven't implemented as it's an edge case - maybe for release 2) is the interpretation of the Utterance from the Google Text to Speech Engine. The Request you've linked to is actually a request to SEND text to the API rather than a RECEIVE. This is why we need to use polly to go from voice>text>voice>text
I going to close this issue (not because it isn't a good idea!) but merely because it isn't supported by the Google API

**Comment by daniel-stoneuk** [comment]
Thanks for the time and skill again
