### ISSUE TITLE
Google Play Music

### ISSUE THREAD

**Issue by 2relativ** [tartanguru/alexa-assistant#50]
Hi there,

I have read threw the FAQ but I didn't notice it there so I am asking this question.
Am I the only one having trouble to play Music from Google Play Music?
I do as following:
"Alexa open google"
*google assistant asks a silly question
"play AC/DC"
*google assistant says that she doesn't understand that.

I haven't tried another music service yet because I have an Play music abonnement.
Thanks for your help.

**Comment by 2relativ** [comment]
Just to add some things... 
I noticed also, that the most features of the assistant doesn't work.
Like controlling my chromecast.
But I can control everything with my assistant on my phone.

**Comment by tartanguru** [comment]
The Google Assistant API that the skill uses doesn’t support these features
at the moment
