### ISSUE TITLE
Error in sending response

### ISSUE THREAD

**Issue by santosh-tas** [tartanguru/alexa-assistant#51]
Hi, 
I am getting this error in my lambda logs.
<img width="1255" alt="screen shot 2018-03-13 at 5 11 37 pm" src="https://user-images.githubusercontent.com/8383252/37339740-ac96f232-26e1-11e8-8e2a-787d46f0ddcd.png">

**Comment by tartanguru** [comment]
Ok - it looks Indian English isn't supported by the Assistant API.
Can you please follow the instructions for installing the Google Assistant
app on your phone and change the assistant language to English(UK) or
English (United States) and see if that fixes the issue?
If that does then I will fix the bug in the code

**Comment by tartanguru** [comment]
Still waiting for feedback

**Comment by oemaix** [comment]
I also have this problem.
![image](https://user-images.githubusercontent.com/8653094/38778627-0730cbba-40ef-11e8-9783-18fc61d59d62.png)
![image](https://user-images.githubusercontent.com/8653094/38778621-de54a3f6-40ee-11e8-871e-8a7ee8516c0f.png)

`{
    "interactionModel": {
        "languageModel": {
            "invocationName": "google",
            "intents": [
                {
                    "name": "AMAZON.CancelIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.HelpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.StopIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.NavigateSettingsIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.MoreIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.PageDownIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.PageUpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollDownIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollLeftIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollRightIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollUpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.NextIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.PreviousIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.YesIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.NoIntent",
                    "samples": []
                },
                {
                    "name": "SearchIntent",
                    "slots": [
                        {
                            "name": "search",
                            "type": "SEARCH"
                        }
                    ],
                    "samples": [
                        "search"
                    ]
                },
                {
                    "name": "AMAZON.NavigateHomeIntent",
                    "samples": []
                }
            ],
            "types": [
                {
                    "name": "SEARCH",
                    "values": [
                        {
                            "name": {
                                "value": "why is the sky blue"
                            }
                        },
                        {
                            "name": {
                                "value": "who is the queen"
                            }
                        }
                    ]
                }
            ]
        }
    }
}`

**Comment by tartanguru** [comment]
It looks like the skill isn’t recieving any text from the Alexa voice recognition.
The skill is saying that you are located in the US - is this correct?
If so is your device set to US English and the skill set-up in us English too?

**Comment by oemaix** [comment]
I am not in the US, but I set the location to US, and the language to US English. I asked Alexa where are we, she thinks I am located in Seato, California. The skill is also set-up in US English. I guess maybe there's something wrong about my interaction model, but I am not sure about that.

**Comment by tartanguru** [comment]
I’ve just spotted the issue with your JSON. 
The samples parameter for the SearchIntent intent is incorrectly formatted in your JSON.
If you use my JSON from above then the skill should work ok

**Comment by oemaix** [comment]
It works!
Thanks!
