### ISSUE TITLE
New Alexa Skills Kit Format

### ISSUE THREAD

**Issue by NARCO515** [tartanguru/alexa-assistant#52]
It appears Alexa Skills web pages have changed making instructions 10 to 22 difficult for the less technical of us to follow.  Are you aware and do you have any plans to update in the near future, please?

**Comment by funkydan2** [comment]
@NARCO515 - I just set this up using the new Developers Console today. [I've started a discussion about this over on the instructions repository](https://github.com/tartanguru/alexa-assistant-instructions/issues/13). 

Did you get everything setup? (If you've got problems, it might be better to start a thread over on the [instructions](https://github.com/tartanguru/alexa-assistant-instructions/issues/) repo.)

**Comment by NARCO515** [comment]
Thanks @funkydan2, when logging back in today I discovered an option to exit the new Developers Console which allowed me to follow the original setup instructions.  Cheers!
