### ISSUE TITLE
New Developer Console - things have changed

### ISSUE THREAD

**Issue by LemmeDasker** [tartanguru/alexa-assistant#54]
Hi
I have just tried to install this skill, following the detailed instructions. But something has changed.
It appears to me that Amazon have switched completely to the new Developer Console, so the instructions are no longer valid. For example, following the instruction "Global Fields section, set the "Render Template"", the new console are showing "Video App" instead.

Also, it seems that the JSON format has changed, as an error occurs when I copy the JSON string into the new "JSON editor" and try to save.

Would it be possible to update both the skill and installation instructions?

Best regards
Flemming

**Comment by jpawlowski** [comment]
See here:
https://github.com/tartanguru/alexa-assistant-instructions/issues/13

**Comment by LemmeDasker** [comment]
Yes - I saw funkydan2's instructions. He provided the updated JSON file. He also wrote this:
If you think people would find it helpful I'd be happy to put the screenshots in the documentation.

I would highly recommend that you accept his offer to update the documentation. It seems that he have the screenshots ready.

Best regards
Flemming

**Comment by tartanguru** [comment]
Hi - this is an issue with the instructions rather than the skill itself so I'm going to close this issue but keep open the one in the instructions project

https://github.com/tartanguru/alexa-assistant-instructions/issues/13
