### ISSUE TITLE
code 3 metadata_internal_wrapper

### ISSUE THREAD

**Issue by haempy** [tartanguru/alexa-assistant#58]
Hello,

by asking "Alexa, starte google" the GoogleAssistand says "Hey, was kann ich für dich tun"
After asking somthing Alexa says:
"the google api returned an error which was code 3 metadata_internal_wrapper"

**Comment by Seme100** [comment]
this ist the Interaction Model. I cannot copy the one from the installation options, the new frontent of developer doesn't accept this. I can only choos amazon Intents and do like this:

`{
    "interactionModel": {
        "languageModel": {
            "invocationName": "google",
            "intents": [
                {
                    "name": "AMAZON.NavigateSettingsIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.MoreIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.PageDownIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.PageUpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollRightIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.MoreIntent",
                    "samples": [
                        "erzähle mehr"
                    ]
                },
                {
                    "name": "AMAZON.NavigateHomeIntent",
                    "samples": [
                        "Gehe zur Hauptseite"
                    ]
                },
                {
                    "name": "AMAZON.NavigateSettingsIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.NextIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.PageUpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.PageDownIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.PreviousIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollRightIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollDownIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollLeftIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.ScrollUpIntent",
                    "samples": []
                },
                {
                    "name": "search",
                    "slots": [
                        {
                            "name": "search",
                            "type": "AMAZON.SearchQuery"
                        }
                    ],
                    "samples": []
                }
            ],
            "types": [
                {
                    "name": "AMAZON.SearchQuery",
                    "values": [
                        {
                            "name": {
                                "value": "warum ist der himmel blau"
                            }
                        },
                        {
                            "name": {
                                "value": "wer ist die queen"
                            }
                        }
                    ]
                }
            ]
        }
    }
}`

**Comment by tartanguru** [comment]
Closing as the skill instructions have been updated with the new Amazon intent models
