### ISSUE TITLE
"I'm not sure what you said, can you repeat please?"

### ISSUE THREAD

**Issue by tommydick** [tartanguru/alexa-assistant#59]
After installing on my Echo show, the Google Assistant initiates and says "Hello, how can I help?, but no matter what I say afterwards, I get the response "I'm not sure what you said, can you repeat please?."

**Comment by tartanguru** [comment]
Is the "I'm not sure what you said, can you repeat please?." in the Google
Assistant voice or Alexa one?

Also what language have you set the skill to?

**Comment by davidemiley** [comment]
I think it was the Google Assistant talking.

I fixed it thusly:

First, I had used an older set of instructions to create the skill, specifically 
http://alexamods.com/guide-install-google-assistant-alexa-skill/

I looked over the correct instruction on this site
https://github.com/tartanguru/alexa-assistant-instructions/blob/master/fresh_install.md

I repeated steps 5, 10, and 17 and that fixed it.

I may later delete the skill and start from fresh just for good measure.

**Comment by tartanguru** [comment]
Glad you got it working - I only really recommend using the instructions
from my Github

**Comment by tommydick** [comment]
The above procedure worked for me as well. 
Thanks

**Comment by dvdcd** [comment]
Someone wanna close this issue?
