### ISSUE TITLE
"Ask google" didn't work anymore

### ISSUE THREAD

**Issue by unfassbarstephan** [tartanguru/alexa-assistant#60]
There are problems since a few days, although it worked great before.  When I say "ask google" in German. Alexa answers the following: "I can't do a Google search. You can ask me your question, and if I can't answer it, I'll do a search with Bing in the Alexa app."

Are there any solutions?

**Comment by tartanguru** [comment]
Try changing the innovation name to something other than Google and see if
that solves the issue

**Comment by unfassbarstephan** [comment]
Changing the codeword to "google assitant" worked fine.
