### ISSUE TITLE
Any plans to add google music here?

### ISSUE THREAD

**Issue by alihashim** [tartanguru/alexa-assistant#63]
It would be fantastic if it was possible to add Google music to the list of functionalities for this skill.

I can see in the logs that an audio response is generated and the size of the file is given and it even says "steaming mp3 file to s3"
If only it would make it's way all the way to alexa

**Comment by tartanguru** [comment]
The Google Assistant API doesn’t currently support music playback so this
isn’t possible.
The skill does produce MP3’s containing the assistants voice response but
this has a maximum length of 30 seconds
