### ISSUE TITLE
Google Project Pending Deletion

### ISSUE THREAD

**Issue by nickcarr79** [tartanguru/alexa-assistant#7]
Ran through the guide and had this working yesterday however today I'm told by Alexa that I need to authorize Google and use the link in the app to do this. Link gives me a 401 error (deleted_client, The OAuth client was deleted). Looked at the Google Cloud Platform and my project has vanished. Is available only under the 'Resources pending deletion' view. I try to Restore it which it says is successful but goes straight back to Pending Deletion.

**Comment by tartanguru** [comment]
May I suggest that you create a new project in the google API console and link that to the skill instead. Otherwise I think you need to raise this issue with Google Support rather than here.

**Comment by JZ-SmartThings** [comment]
I had that too... make sure all of your environment variables and URL's are defined properly in Lambda and Alexa website. My issue was environment variables.

**Comment by tartanguru** [comment]
Not setting the Environment Variables properly will cause a similar error but would not cause the project to be deleted

**Comment by nickcarr79** [comment]
Sorry I realise now this probably wasn't the right place for this issue. However since the trail is here now I'll just update to say that this started working about 6 hours later. Either Google fixed something behind the scenes without being asked or it needed time to re-enable the project even though on screen it said it had been done straight away.
