### ISSUE TITLE
Should this skill support chromecast?

### ISSUE THREAD

**Issue by FASNASTIC** [tartanguru/alexa-assistant#70]
Ask a Google Home, or Google Assistant on Android or iOS device "OK Google, watch cat videos on TV" and it will work.

Ask Alexa with this skill "Alexa, Ask google, watch cat videos on TV" - "Sorry, I don't know how to help with that yet"

Any reason why?

**Comment by tartanguru** [comment]
I don't believe this functionality is supported by the Google Assistant API that the skill uses.
Sorry
