### ISSUE TITLE
Having an error: Cannot find module '/var/task/index'

### ISSUE THREAD

**Issue by TheRealNate** [tartanguru/alexa-assistant#8]
Lambda outputs this:

{
  "errorMessage": "Cannot find module '/var/task/index'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:417:25)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)"
  ]
}

And the skill doesn't work. It says something along the lines of "The skill had an error"

**Comment by tartanguru** [comment]
I suspect you have uploaded the wrong zip file. It needs to be the one called index.zip inside the zip that you downloaded from github

**Comment by TheRealNate** [comment]
Yup, that was it.
