### ISSUE TITLE
Cannot create Google Assistant alexa skill on AWS

### ISSUE THREAD

**Issue by Ronaldo93** [tartanguru/alexa-assistant#86]
The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 32b6f147-7c87-11e9-9470-99782a816bdb)".  Any assistance appreciated.

**Comment by hlfritz** [comment]
confirmed.  i WAS able to edit the template and change that portion of the code to nodejs8.10 (in a new window to edit the template while i deleted the failed skill in the original window) and successfully create the skill, but i have a problem with it - "There was a problem with the requested skills response".

i tried looking for the solution shown in troubleshooting but the amazon interface has changed again and there is no render template option that i can find.

willing to help test.

**Comment by hlfritz** [comment]
Just found issue #81 that addresses this and was commented on by developer.  this can probably be closed as a duplicate.
