### ISSUE TITLE
"There was a Problem with Requested Skills Response"

### ISSUE THREAD

**Issue by Starsick** [tartanguru/alexa-assistant#9]
Can you help? I have carefully followed, painstakingly step-by-step the very well-written intructions in trying to invoke this skill with my Echo. I get this response: "There was a Problem with Requested Skills Response" . What do you suppose it could be? I have double-triple and quadruple checked this, step by step. I am really at the point in giving you my credentials and see if you can set it up for me.   :-)  Can you point me in the right direction? I have saved all of the developer pages, info needing to be copied and pasted into a notepad file. Please let me know if you can help. The ONE difference between your instructions and how I did this function was that the Assistant API was already enabled  on my Cloud, and if I clicked on your link in the Tutorial it would just appear at my Developer Page and hang. When I went in from my developer page it did NOT have the "embeddedassistant" in the URL and there was no way to change it and make it work, I therefore created the function from my main developer page and being sure the Assistant API is enabled (it is).  
![image](https://user-images.githubusercontent.com/30006150/27987802-f7062d24-63e1-11e7-98af-805d4d68c7c2.png)

![image](https://user-images.githubusercontent.com/30006150/27987816-2f21e95a-63e2-11e7-81ae-4711e02c6c19.png)

**Comment by Starsick** [comment]
Ha! After searching for a video tutorial - I found the answer! (Thanks to Paul Hibbert!!!!) All users - you need to UNZIP the Master Archive file and upload the INDEX.ZIP file within the archive to you Lambda Function (Alexa Skill). If it was in the EXCELLENT step-by-step provided by tatanguru, I apologize. THIS FUNCTION NOW WORKS PERFECT! The best of both worlds - Google SEARCH and ECHO Functionality - Skills!!

**Comment by tartanguru** [comment]
It is mentioned in the written instructions but glad you got it working:-

"Click on the "Upload" button. Go to the folder where you unzipped the
files you downloaded from Github, select index.zip and click open. Do not
upload the alexa-assistant-master.zip you downloaded from Github - only the
index.zip contained within it."

**Comment by Starsick** [comment]
Yep-my fault. Sorry ... works great!


[image: photo]
Creative Director, Wondermous Media Productions
p:304-933-9862 | m:304-365-3475 | w:http://wondermousmedia.com
Get your own email signature
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg64J7jYMfmJxFdnF1MW1p7Y5W56dNgCf4B5LTM02?t=https%3A%2F%2Fwisestamp.com%2Femail-install%3Futm_source%3Dpromotion%26utm_medium%3Dsignature%26utm_campaign%3Dget_your_own&si=6590203080212480&pi=3d18c10e-4425-4fea-9c37-42f497890930>
