### ISSUE TITLE
"There was a problem with the requested skill's response"

### ISSUE THREAD

**Issue by jeffyjeffy1023** [tartanguru/alexa-assistant#97]
Hi! I did everything the tutorial said to do, and I get that error. (also I had to change the cloudformation  JSON to nodejs12.x because otherwise the stack wouldn't build) I went to use the problem fixing guide but.... I can't find the information tab! Am I just stupid or did the remove it?

**Comment by rokmohar** [comment]
Hi.

The problem is because the code is not compatible with NodeJS 10.x and 12.x, which is now supported on AWS Lambda eco-system.

Just changing the cloudformation to 12.x won't help. I've had the same issue a few days ago and fixed it myself. You can check the code here and build & deploy it yourself with Docker, just follow the Build & Deploy section:
https://github.com/rokmohar/alexa-assistant/tree/feature/nodejs10.x

I've tested it with NodeJS 10.x and it works well, not sure if it works with 12.x, you are free to try, but make sure that you set NODE_TARGET to 12 when you build the code.

I've also upgraded the node libraries and refactored a code a bit, you can check it on the master branch:
https://github.com/rokmohar/alexa-assistant

**Comment by jeffyjeffy1023** [comment]
Alright, cool. Do I have to start from the ground up or do I just replace the cloud stack?

**Comment by rokmohar** [comment]
Please check my recent comment here: https://github.com/tartanguru/alexa-assistant/issues/95#issuecomment-629855677

You've already done the first part (changing to nodejs12.x), except I'd suggest you go to your AWS Lambda function and change to nodejs10.x there -- no need to re-create the stack. Then follow the steps from there.

When I have some time I could upload the built ZIP file and updated cloudformation.json to S3 bucket so you (and others) can just copy-paste it like in the instructions from tartanguru.

**Comment by HeyboyOne** [comment]
That would  be amazing!

**Comment by HeyboyOne** [comment]
If you had do this, please message me here or in my comment. I would be so greatfull.

**Comment by jeffyjeffy1023** [comment]
...Is there a way to make it without docker? I am fine with using CMD for things, but docker and git are totally new to me. Sure, I've heard of git and docker but I've never used them before.

**Comment by rokmohar** [comment]
It should work if you run commands from the Dockerfile:

npm install --only=prod
npm rebuild --target=${NODE_TARGET} --target_arch=x64 --target_platform=linux --target_libc=glibc

Then you need to ZIP the node_modules, proto, speechAssets folders and index.js file.

I did this on Windows and the ZIP file after zipping it was 190MB (did it with both CMD and WSL), but AWS Lambda hasu upload limit of 50MB. Might work better if you run it on Linux distro like Ubuntu or Debian -- you can try this.

**Comment by jeffyjeffy1023** [comment]
Uh oh.

Docker barfed out this gobbledegook. What does it mean?

C:\Users\jeffy\Desktop\Tools\googlexarepo>docker build -t mylambda .
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/build?bui
ldargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&
cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&n
etworkmode=default&rm=1&session=is5quiuz6oomfyk2xtbtjazse&shmsize=0&t=mylambda&t
arget=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot fi
nd the file specified. In the default daemon configuration on Windows, the docke
r client must be run elevated to connect. This error may also indicate that the
docker daemon is not running.

**Comment by rokmohar** [comment]
Do you use Docker with Hyper-V or Docker Toolbox for VirtualBox? It would be best if you take a look at the Docker github repo: https://github.com/docker/for-win/issues/1738

To make it easer I've uploaded the ZIP to the releases on my repo:
https://github.com/rokmohar/alexa-assistant/releases/tag/v1.0

Just download the file and upload it to your AWS Lambda function.

**Comment by jeffyjeffy1023** [comment]
I installed docker using the docker toolbox since I use windows 7. Thank you!

**Comment by rokmohar** [comment]
On docker toolbox you must start the docker machine with this command:
docker-machine start

You may also need to run:
docker-machine env

And copy the lines from there. Be careful last line has REM in front, copy only the command without the REM.

I have to do these steps everytime I restart the PC.

**Comment by jeffyjeffy1023** [comment]
Ah. I see. Well, the skill works now! Thanks man. I'll be closing this issue now. Bye!

**Comment by Ender3Pro** [comment]
Hi, i can't seem to install docker, can you please send me the file you created?
